### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by dfirhoze** [AmgdGocha/DriveFS-Sleuth#15]
ERROR: Could not build wheels for grpcio-tools, which is required to install pyproject.toml-based projects

Got this after running `pip install -r requirements.txt` on a Windows 11 command prompt.  The python script won't execute correctly without this.  I have the 2022 Dev Tools installed as well.  Any workaround for this or seen anyone with similar errors? Thanks!

**Comment by AmgdGocha** [comment]
Have you tried installing the requirements in a separate virtual environment and running the tool? this error is associated with the underlying infrastructure on which you're executing the tool.

**Comment by dfirhoze** [comment]
Yes, that was attempted as well.  I understand it has nothing to do with the tool itself, just wanted to see if you or anyone else had the same problem while installing these dependencies.  Feel free to close this. Thanks.
