### ISSUE TITLE
Suggestion: add pyproject-toml file

### ISSUE THREAD

**Issue by 0CM** [AmgdGocha/DriveFS-Sleuth#20]
Could you please consider adding pyproject-toml file to you repository, so it can be easily installed via PIP ?

https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

Thank you

**Comment by AmgdGocha** [comment]
Hi @0CM,

Thanks for the suggestion. As of now, there are only two dependencies so I believe that `requirements.txt` is sufficient and straightforward specially for the fellows who are not experienced enough with python, if DriveFS Slueth became more complex, in terms of dependencies, we'll add a `pyproject-toml` file. However, I beleive that the `Readme.md` file needs to be updated to include exact steps to create a new venv and install the dependencies using the `requirements.txt` file to make it easier for whom who is not experienced enough.

Thanks, your suggestion is very much appreciated.

**Comment by AmgdGocha** [comment]
DriveFS Sleuth is now published on PyPi and it can be easily installed as a python package.

**Comment by 0CM** [comment]
Good job and briliant news, thank you very much, will do test the deployment and will let you know how it went.

Have a good day sir!
